insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'꺄ㅎㅎ 열심히 해주신덕분에 !!!! 다음에 더 멋진 모습 기대해보겠습니돠하 ♥ 감사해요>_<','2021-09-03',37);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'에구 후기는 알람이 안떠서 이제봤네용ㅜㅜ 망설이지않으셔도 될정도로 잘 따라와 주셔서 감사해요! 다음에 또 봬용','2021-09-02',35);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'수고하셨습니다 감사합니다','2021-09-04',4);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'감사합니다 ^_^!! 오늘도 행복한 하루 마무리 하세요오!!!!','2021-09-05',42);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'럽유.......ㅎ_ㅎ 담에 더 즐겁게 함께 할 것이라 믿으며...!!! 오늘도 행복한 하루 보내세용!!','2021-09-04',36);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'감사합니다 ^_^!! 오늘도 행복한 하루 마무리 하세요오!!!!','2021-09-03',19);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'그럼 또 오시는걸루...♥ ㅎㅎㅎ 언제든 환영인거알죠??? 감사합니다 ㅎㅎ','2021-09-05',46);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'귀한 후기 작성해주셔서 진심으로 감사드립니다 ^^! 정규강좌까지 수강해주셔서 넘넘 감사합니다 ♡ 앞으로도 한 시간 한 시간 힐링하실 수 있도록 꽉꽉 채워드리겠습니다! 진심으로 감사드립니다.','2021-09-04',26);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'귀한 후기 작성해주셔서 진심으로 감사드립니다 ^^! 정규강좌까지 수강해주셔서 넘넘 감사합니다 ♡ 앞으로도 한 시간 한 시간 힐링하실 수 있도록 꽉꽉 채워드리겠습니다! 진심으로 감사드립니다.','2021-09-04',48);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'예쁜후기 남겨주셔서 감사해요오 운동신경짱!!','2021-09-05',12);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'럽유.......ㅎ_ㅎ 담에 더 즐겁게 함께 할 것이라 믿으며...!!! 오늘도 행복한 하루 보내세용!!','2021-09-02',50);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'수강생님과 힐링하며 함께 연주할 수 있어서 너무 행복했습니다.','2021-09-04',6);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'ㅎㅎ 감사합니다~~!! 다음에 또 놀러와주세요옹','2021-09-04',47);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'흐흐 ㅎㅎ 엄청난 유쾌했던분 맞으신가요...⭐️ 헤헤 ㅎㅎ 감사합니다 또오세요 언제든 대환영이니까~~~♥ ♥ 항상 건강 조심하세요 ㅎㅎ','2021-09-05',48);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'흐흐 ㅎㅎ 엄청난 유쾌했던분 맞으신가요...⭐️ 헤헤 ㅎㅎ 감사합니다 또오세요 언제든 대환영이니까~~~♥ ♥ 항상 건강 조심하세요 ㅎㅎ','2021-09-05',33);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'우와 후기 예쁘게 작성해주셔서 감사합니다 :)
처음 하신다고 하셨는데, 너무 잘 따라와주셔서 저도 재밌는 수업시간 이였어요! 얼른 또 봬요ㅎㅎ','2021-09-04',10);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'감사합니다 천사님 >_< 열심히 해주셔서 더 기뻤어요 ㅎㅎ','2021-09-03',28);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'귀한 후기 작성해주셔서 진심으로 감사드립니다 ^^! 정규강좌까지 수강해주셔서 넘넘 감사합니다 ♡ 앞으로도 한 시간 한 시간 힐링하실 수 있도록 꽉꽉 채워드리겠습니다! 진심으로 감사드립니다.','2021-09-05',21);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'ㅎㅎ 감사합니다~~!! 다음에 또 놀러와주세요옹','2021-09-05',30);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'에구 후기는 알람이 안떠서 이제봤네용ㅜㅜ 망설이지않으셔도 될정도로 잘 따라와 주셔서 감사해요! 다음에 또 봬용','2021-09-04',1);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'ㅎㅎ 웃음이 많으셔서 수업하면서도 기분이좋았어요!! 코로나 항상 조심하시고 좋은하루 되세요! 또 봬용 :)','2021-09-04',36);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'귀한 후기 작성해주셔서 진심으로 감사드립니다 ^^! 정규강좌까지 수강해주셔서 넘넘 감사합니다 ♡ 앞으로도 한 시간 한 시간 힐링하실 수 있도록 꽉꽉 채워드리겠습니다! 진심으로 감사드립니다.','2021-09-04',45);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'예쁜후기 남겨주셔서 감사해요오 운동신경짱!!','2021-09-02',26);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'럽유.......ㅎ_ㅎ 담에 더 즐겁게 함께 할 것이라 믿으며...!!! 오늘도 행복한 하루 보내세용!!','2021-09-03',20);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'그럼 또 오시는걸루...♥ ㅎㅎㅎ 언제든 환영인거알죠??? 감사합니다 ㅎㅎ','2021-09-05',31);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'재미있으셨다니 행복해요 -!!!! 다음에 또 봬요>_< ♥ ♥','2021-09-03',26);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'꺄 ㅎㅎ 열심히 해주셔서 넘넘 행복했어요!!! 항상 코로나 조심하시구 좋은날 다시봬요 ㅎㅎ ♥','2021-09-04',20);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'그럼 또 오시는걸루...♥ ㅎㅎㅎ 언제든 환영인거알죠??? 감사합니다 ㅎㅎ','2021-09-03',30);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'ㅎㅎ 감사합니다~~!! 다음에 또 놀러와주세요옹','2021-09-03',39);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'ㅎㅎ 감사합니다~~!! 다음에 또 놀러와주세요옹','2021-09-05',38);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'럽유.......ㅎ_ㅎ 담에 더 즐겁게 함께 할 것이라 믿으며...!!! 오늘도 행복한 하루 보내세용!!','2021-09-02',28);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'럽유.......ㅎ_ㅎ 담에 더 즐겁게 함께 할 것이라 믿으며...!!! 오늘도 행복한 하루 보내세용!!','2021-09-02',12);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'수고하셨습니다 감사합니다','2021-09-04',40);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'흐흐 감사합니다-!!!! 담에 또 놀러와주세요>_< 언제나 대환영이라규용!!!! 알죠~? ♥','2021-09-05',1);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'재미있으셨다니 행복해요 -!!!! 다음에 또 봬요>_< ♥ ♥','2021-09-03',24);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'수고하셨습니다 감사합니다','2021-09-05',14);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'재미있으셨다니 행복해요 -!!!! 다음에 또 봬요>_< ♥ ♥','2021-09-04',21);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'꺄 ㅎㅎ 열심히 해주셔서 넘넘 행복했어요!!! 항상 코로나 조심하시구 좋은날 다시봬요 ㅎㅎ ♥','2021-09-03',41);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'꺄 ㅎㅎ 열심히 해주셔서 넘넘 행복했어요!!! 항상 코로나 조심하시구 좋은날 다시봬요 ㅎㅎ ♥','2021-09-04',8);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'예쁜후기 남겨주셔서 감사해요오 운동신경짱!!','2021-09-04',15);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'꺄 ㅎㅎ 열심히 해주셔서 넘넘 행복했어요!!! 항상 코로나 조심하시구 좋은날 다시봬요 ㅎㅎ ♥','2021-09-05',5);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'우와 후기 예쁘게 작성해주셔서 감사합니다 :)
처음 하신다고 하셨는데, 너무 잘 따라와주셔서 저도 재밌는 수업시간 이였어요! 얼른 또 봬요ㅎㅎ','2021-09-02',28);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'꺄ㅎㅎ 열심히 해주신덕분에 !!!! 다음에 더 멋진 모습 기대해보겠습니돠하 ♥ 감사해요>_<','2021-09-05',41);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'흐흐 ㅎㅎ 엄청난 유쾌했던분 맞으신가요...⭐️ 헤헤 ㅎㅎ 감사합니다 또오세요 언제든 대환영이니까~~~♥ ♥ 항상 건강 조심하세요 ㅎㅎ','2021-09-04',15);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'에구 후기는 알람이 안떠서 이제봤네용ㅜㅜ 망설이지않으셔도 될정도로 잘 따라와 주셔서 감사해요! 다음에 또 봬용','2021-09-04',25);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'수강생님과 힐링하며 함께 연주할 수 있어서 너무 행복했습니다.','2021-09-04',47);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'재미있으셨다니 행복해요 -!!!! 다음에 또 봬요>_< ♥ ♥','2021-09-03',36);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'그럼 또 오시는걸루...♥ ㅎㅎㅎ 언제든 환영인거알죠??? 감사합니다 ㅎㅎ','2021-09-05',25);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'수고하셨습니다 감사합니다','2021-09-04',33);
insert into tblReviewReply(reviewReplySeq,content,regdate,classReviewSeq) values(seqReviewReply.nextVal,'그럼 또 오시는걸루...♥ ㅎㅎㅎ 언제든 환영인거알죠??? 감사합니다 ㅎㅎ','2021-09-05',50);
